# Generated by Django 2.0.3 on 2018-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koinuser',
            name='auth_complete',
            field=models.BooleanField(default=False),
        ),
    ]
